# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99e888be03bb334c343440ba13455d5459800f587aa1ea97f65bc8b4ad7cab78e9a38c6a49be890ac22461fb051104a110e800ceef518b405dbbce0d2dab6e74

test:
  secret_key_base: 417594c858fe23934747a0c31242f1ead4c0c8373165efcea78404e38d6b77e00a1241acc75406c83f11e8bdf01a9ac822629c949a000a4e41589db8b952c932

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
